name: Algol
favicon: null
layout_spectrum: 0.44836
typography_spectrum: 0.48377
title: Alberto Krone-Martins - Personal Webpage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#110b04'
    - '#ce7f48'
    - '#a34200'
    - '#ffcc49'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
