name: Algol
favicon: null
layout_spectrum: 0.99875
typography_spectrum: 0.61529
title: Alberto Krone-Martins Personal Webpage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dbdbdb'
    - '#919191'
    - '#fcfcfc'
    - '#313131'
  brandStrength: 0.5090774036943913
  lightness: 0.14954169047996402
  saturation: 0.6157016709912568
  rhythmicContrast: 0.5841386797837913
purpose: []
